# Generated by Django 2.1 on 2019-07-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.IntegerField()),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
    ]
